# Generated by Django 4.1.9 on 2023-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
