# Generated by Django 4.1.9 on 2023-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0002_alter_product_category_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
