# Generated by Django 4.1.9 on 2023-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
