# Generated by Django 4.1.9 on 2023-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0004_productcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
