# Generated by Django 4.1.9 on 2023-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
