# Generated by Django 4.1.9 on 2023-06-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0001_initial'),
        ('ecommerce_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='ecommerce_products.product', verbose_name='product_id'),
        ),
    ]
