# Generated by Django 4.1.9 on 2023-06-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_cart', '0002_alter_cartproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='shopping_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='ecommerce_cart.shoppingsession', verbose_name='shopping_session_id'),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_session', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
