# Generated by Django 4.1.9 on 2023-07-07 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_cart', '0004_alter_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
